# -*- coding: utf-8 -*-
"""PROGRAM 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NWk_WeQ0AvKODCTlIdFizjnEPzbfDBYZ
"""

!pip install streamlit

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import streamlit as st
# 
# st.title("Program 2: Gradient Descent Interaktif (Linear Regression)")
# 
# # === Upload / load data ===
# st.sidebar.header("Dataset")
# uploaded_file = st.sidebar.file_uploader("Upload data CSV (kolom x dan y)", type=["csv"])

from google.colab import files

# for upload dataset to google colab

uploaded = files.upload()

# === Upload / load data ===
st.sidebar.header("Dataset")
uploaded_file = st.sidebar.file_uploader("Upload data CSV (kolom x dan y)", type=["csv"])

# === Upload / load data ===
st.sidebar.header("Dataset")
uploaded_file = st.sidebar.file_uploader("Upload data CSV (kolom x dan y)", type=["csv"])

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
else:
    # Contoh data default (boleh kamu ganti dengan data.csv dari GitHub)
    data = pd.DataFrame({
        "x": [1, 2, 3, 4, 5],
        "y": [2, 4, 5, 4, 5]
    })

st.write("Data yang digunakan:")
st.dataframe(data)

X = data["x"].values
y = data["y"].values
n = len(X)

# === Fungsi cost dan gradient ===
def compute_cost(m, b, X, y):
    y_pred = m * X + b
    return (1 / (2 * n)) * np.sum((y - y_pred) ** 2)

def gradient_descent(X, y, m_init, b_init, lr, n_iter):
    m = m_init
    b = b_init
    cost_history = []

    for i in range(n_iter):
        y_pred = m * X + b
        dm = (-2 / n) * np.sum(X * (y - y_pred))
        db = (-2 / n) * np.sum(y - y_pred)

        m = m - lr * dm
        b = b - lr * db

        cost_history.append(compute_cost(m, b, X, y))
    return m, b, cost_history

# === Sidebar: parameter interaktif ===
st.sidebar.header("Parameter Gradient Descent")
lr = st.sidebar.number_input("Learning rate", min_value=0.0001, max_value=1.0, value=0.01, step=0.01, format="%.4f")
n_iter = st.sidebar.number_input("Jumlah iterasi", min_value=10, max_value=10000, value=1000, step=10)
m_init = st.sidebar.number_input("m awal", value=0.0, format="%.4f")
b_init = st.sidebar.number_input("b awal", value=0.0, format="%.4f")

x_new = st.number_input("Masukkan nilai x untuk diprediksi", value=3.0, format="%.2f")

# === Jalankan training saat tombol ditekan ===
if st.button("Jalankan Gradient Descent"):
    m_final, b_final, cost_history = gradient_descent(X, y, m_init, b_init, lr, n_iter)

    st.subheader("Hasil Parameter")
    st.write(f"m akhir = **{m_final:.4f}**")
    st.write(f"b akhir = **{b_final:.4f}**")
    st.write(f"Cost terakhir = **{cost_history[-1]:.6f}**")

    # Prediksi
    y_pred_new = m_final * x_new + b_final
    st.subheader("Prediksi")
    st.write(f"Prediksi y untuk x = {x_new} adalah **{y_pred_new:.4f}**")

    # Plot data + garis regresi
    fig1, ax1 = plt.subplots()
    ax1.scatter(X, y, label="Data asli")
    x_line = np.linspace(min(X), max(X), 100)
    y_line = m_final * x_line + b_final
    ax1.plot(x_line, y_line, color="red", label="Regresi (GD)")
    ax1.set_xlabel("x")
    ax1.set_ylabel("y")
    ax1.set_title("Data & Garis Regresi")
    ax1.legend()
    st.pyplot(fig1)

    # Plot cost vs iterasi
    fig2, ax2 = plt.subplots()
    ax2.plot(range(1, len(cost_history)+1), cost_history)
    ax2.set_xlabel("Iterasi")
    ax2.set_ylabel("Cost")
    ax2.set_title("Perkembangan Cost")
    st.pyplot(fig2)

