# -*- coding: utf-8 -*-
"""PROGRAM 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NWk_WeQ0AvKODCTlIdFizjnEPzbfDBYZ
"""

!pip install streamlit

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st

st.title("Program 2: Gradient Descent Interaktif (Linear Regression)")

# === Load data ===
data = pd.read_csv('data.csv')  # pastikan data.csv sudah ada di /content
st.write("Data yang digunakan:")
st.dataframe(data)

X = data["x"].values
y = data["y"].values
n = len(X)

def compute_cost(m, b, X, y):
    y_pred = m * X + b
    return (1 / (2 * n)) * np.sum((y - y_pred) ** 2)

def gradient_descent(X, y, m_init, b_init, lr, n_iter):
    m = m_init
    b = b_init
    cost_history = []
    for i in range(n_iter):
        y_pred = m * X + b
        dm = (-2 / n) * np.sum(X * (y - y_pred))
        db = (-2 / n) * np.sum(y - y_pred)
        m = m - lr * dm
        b = b - lr * db
        cost_history.append(compute_cost(m, b, X, y))
    return m, b, cost_history

st.sidebar.header("Parameter Gradient Descent")
lr = st.sidebar.number_input("Learning rate", min_value=0.0001, max_value=1.0, value=0.01, step=0.01, format="%.4f")
n_iter = st.sidebar.number_input("Jumlah iterasi", min_value=10, max_value=10000, value=1000, step=10)
m_init = st.sidebar.number_input("m awal", value=0.0, format="%.4f")
b_init = st.sidebar.number_input("b awal", value=0.0, format="%.4f")

x_new = st.number_input("Masukkan nilai x untuk diprediksi", value=3.0, format="%.2f")

if st.button("Jalankan Gradient Descent"):
    m_final, b_final, cost_history = gradient_descent(X, y, m_init, b_init, lr, n_iter)
    st.subheader("Hasil Parameter")
    st.write(f"m akhir = {m_final:.4f}")
    st.write(f"b akhir = {b_final:.4f}")
    st.write(f"Cost terakhir = {cost_history[-1]:.6f}")

    y_pred_new = m_final * x_new + b_final
    st.subheader("Prediksi")
    st.write(f"Prediksi y untuk x = {x_new} adalah {y_pred_new:.4f}")

    fig1, ax1 = plt.subplots()
    ax1.scatter(X, y, label="Data asli")
    x_line = np.linspace(min(X), max(X), 100)
    y_line = m_final * x_line + b_final
    ax1.plot(x_line, y_line, color="red", label="Regresi (GD)")
    ax1.legend()
    st.pyplot(fig1)

    fig2, ax2 = plt.subplots()
    ax2.plot(range(1, len(cost_history)+1), cost_history)
    ax2.set_xlabel("Iterasi")
    ax2.set_ylabel("Cost")
    ax2.set_title("Perkembangan Cost")
    st.pyplot(fig2)

code = """import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st

st.title("Program 2: Gradient Descent Interaktif (Linear Regression)")

# === Load data ===
try:
    data = pd.read_csv('data.csv')
    # Check if 'x' and 'y' columns exist, if not, try to rename generic columns
    if 'x' not in data.columns and 'y' not in data.columns and len(data.columns) >= 2:
        data.columns = ['x', 'y'] + list(data.columns[2:]) # Rename first two columns to x, y
    elif 'x' not in data.columns or 'y' not in data.columns:
        st.error("Error: 'data.csv' must contain 'x' and 'y' columns.")
        st.stop() # Stop Streamlit app if critical columns are missing
except FileNotFoundError:
    st.error("Error: 'data.csv' not found. Please upload the data file.")
    st.stop()
except Exception as e:
    st.error(f"Error loading data: {e}")
    st.stop()

st.write("Data yang digunakan:")
st.dataframe(data)

X = data["x"].values
y = data["y"].values
n = len(X)

def compute_cost(m, b, X, y):
    y_pred = m * X + b
    return (1 / (2 * n)) * np.sum((y - y_pred) ** 2)

def gradient_descent(X, y, m_init, b_init, lr, n_iter):
    m = m_init
    b = b_init
    cost_history = []
    for i in range(n_iter):
        y_pred = m * X + b
        dm = (-2 / n) * np.sum(X * (y - y_pred))
        db = (-2 / n) * np.sum(y - y_pred)
        m = m - lr * dm
        b = b - lr * db
        cost_history.append(compute_cost(m, b, X, y))
    return m, b, cost_history

st.sidebar.header("Parameter Gradient Descent")
lr = st.sidebar.number_input("Learning rate", min_value=0.0001, max_value=1.0, value=0.01, step=0.01, format="%.4f")
n_iter = st.sidebar.number_input("Jumlah iterasi", min_value=10, max_value=10000, value=1000, step=10)
m_init = st.sidebar.number_input("m awal", value=0.0, format="%.4f")
b_init = st.sidebar.number_input("b awal", value=0.0, format="%.4f")

x_new = st.number_input("Masukkan nilai x untuk diprediksi", value=3.0, format="%.2f")

if st.button("Jalankan Gradient Descent"):
    m_final, b_final, cost_history = gradient_descent(X, y, m_init, b_init, lr, n_iter)
    st.subheader("Hasil Parameter")
    st.write(f"m akhir = {m_final:.4f}")
    st.write(f"b akhir = {b_final:.4f}")
    st.write(f"Cost terakhir = {cost_history[-1]:.6f}")

    y_pred_new = m_final * x_new + b_final
    st.subheader("Prediksi")
    st.write(f"Prediksi y untuk x = {x_new} adalah {y_pred_new:.4f}")

    fig1, ax1 = plt.subplots()
    ax1.scatter(X, y, label="Data asli")
    x_line = np.linspace(min(X), max(X), 100)
    y_line = m_final * x_line + b_final
    ax1.plot(x_line, y_line, color="red", label="Regresi (GD)")
    ax1.legend()
    st.pyplot(fig1)

    fig2, ax2 = plt.subplots()
    ax2.plot(range(1, len(cost_history)+1), cost_history)
    ax2.set_xlabel("Iterasi")
    ax2.set_ylabel("Cost")
    ax2.set_title("Perkembangan Cost")
    st.pyplot(fig2)
"""

with open("program_2.py", "w") as f:
    f.write(code)
print("program_2.py berhasil dibuat!")